# Generated by Django 5.0.2 on 2024-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.FileField(upload_to='subcategory_images/'),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='document',
            field=models.FileField(upload_to='subsubcategory_documents/'),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='image',
            field=models.FileField(upload_to='subsubcategory_images/'),
        ),
    ]
