# Generated by Django 5.0.2 on 2024-03-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_categories_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='document',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='image',
            field=models.URLField(),
        ),
    ]
